### ISSUE TITLE
Review 1: Buatlah readme

### ISSUE THREAD

**Issue by priyandari** [Alifyanarza/UAS_Kelompok8#1]
Agar team tahu mana yang program untuk dieksekusi, mana program refereni, dll

Setelah iu baru akan direview 1 lagi

**Comment by priyandari** [comment]
File yang akan dieksekusi pengguna file yang mana ?
Contoh eksekusinya seperti apa ?

**Comment by priyandari** [comment]
Setelah dijelaskan review lagi

**Comment by Alifyanarza** [comment]
Readme sudah dibuatkan pak
