### ISSUE TITLE
Pemilihan tujuan, pemilihan jenis kelas, dan menampilkan data kereta yang tersedia berserta tarifnya

### ISSUE THREAD

**Issue by priyandari** [Alifyanarza/UAS_Kelompok8#5]
Pemilihan tujuan, pemilihan jenis kelas, dan menampilkan data kereta yang tersedia berserta tarifnya

**Comment by priyandari** [comment]
Dengan adanya tampilan tarif kereta, maka kemudian pengguna akan menginput jumlah orang misalkan

**Comment by priyandari** [comment]
Atau perhatikan alur kerja pemesanan tiket di stasiun

**Comment by AprilliaDebrial** [comment]
Sudah diperbaiki dengan menambahkan pemilihan kereta beserta tarifnya dan  pengguna dapat menginput jumlah tiket yang akan dipesan
